### ISSUE TITLE
dayjs() Type error occured

### ISSUE THREAD

**Issue by yeonjulee1005** [fumeapp/dayjs#16]
I'm using `nuxt-dayjs@1.1.2`

```
------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.7.3
- CLI Version:      3.9.0
- Nitro Version:    2.6.3
- Package Manager:  bun@1.0.1
- Builder:          -
- User Config:      modules, supabase, css, stylelint, components, imports, i18n, pinia, vueuse, typescript, vite, elementPlus, dayjs, runtimeConfig
- Runtime Modules:  @nuxt/devtools@0.8.4, @vueuse/nuxt@10.4.1, @nuxtjs/supabase@1.1.2, @nuxtjs/stylelint-module@5.1.0, @nuxtjs/i18n@8.0.0-rc.4, @nuxt/image@1.0.0-rc.2, @pinia/nuxt@0.4.11, @pinia-plugin-persistedstate/nuxt@1.1.2, @element-plus/nuxt@1.0.6, nuxt-icon@0.5.0, dayjs-nuxt@1.1.2
- Build Modules:    -
```

this is occured type error like below,

<img width="1070" alt="스크린샷 2023-09-25 오전 8 49 51" src="https://github.com/fumeapp/dayjs/assets/57179957/ef494c4e-a710-40de-973d-cc38aca8d974">

**Comment by 7Koston** [comment]
Workaround for now is to change `./node_modules/dayjs-nuxt/dist/runtime/composables/dayjs.d.ts`
to
```typescript
import Dayjs from 'dayjs';
export declare const useDayjs: () => typeof Dayjs;
```

**Comment by acidjazz** [comment]
fixed in v1.1.3 thank you

**Comment by jb-alvarado** [comment]
Can it be, that the error still exist when using `const { $dayjs } = useNuxtApp()`?
